//! Generated by `./gen.rs forward < in.c > out.c`

#include <dirent.h>
#include <poll.h>
#include <sys/mman.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/uio.h>
#include <time.h>
#include <unistd.h>

// dirent.h

ssize_t sys_getdents64(int fd, void *dirp, size_t count);

ssize_t getdents64(int fd, void *dirp, size_t count) {
    ssize_t ret = sys_getdents64(fd, dirp, count);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// poll.h

int sys_poll(struct pollfd *fds, nfds_t nfds, int timeout);

int poll(struct pollfd *fds, nfds_t nfds, int timeout) {
    int ret = sys_poll(fds, nfds, timeout);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/mman.h

int sys_mlock(const void *addr, size_t len);

int mlock(const void *addr, size_t len) {
    int ret = sys_mlock(addr, len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_mlockall(int flags);

int mlockall(int flags) {
    int ret = sys_mlockall(flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_munlock(const void *addr, size_t len);

int munlock(const void *addr, size_t len) {
    int ret = sys_munlock(addr, len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_munlockall(void);

int munlockall(void) {
    int ret = sys_munlockall();

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/socket.h

int sys_accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int accept(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_accept(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_bind(int socket, const struct sockaddr *address, socklen_t address_len);

int bind(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_bind(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_connect(int socket, const struct sockaddr *address, socklen_t address_len);

int connect(int socket, const struct sockaddr *address, socklen_t address_len) {
    int ret = sys_connect(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int getpeername(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getpeername(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len);

int getsockname(int socket, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    int ret = sys_getsockname(socket, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len);

int getsockopt(int socket, int level, int option_name, void *restrict option_value, socklen_t *restrict option_len) {
    int ret = sys_getsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_listen(int socket, int backlog);

int listen(int socket, int backlog) {
    int ret = sys_listen(socket, backlog);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len);

int setsockopt(int socket, int level, int option_name, const void *option_value, socklen_t option_len) {
    int ret = sys_setsockopt(socket, level, option_name, option_value, option_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_shutdown(int socket, int how);

int shutdown(int socket, int how) {
    int ret = sys_shutdown(socket, how);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_socket(int domain, int type, int protocol);

int socket(int domain, int type, int protocol) {
    int ret = sys_socket(domain, type, protocol);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len);

ssize_t recvfrom(int socket, void *restrict buffer, size_t length, int flags, struct sockaddr *restrict address, socklen_t *restrict address_len) {
    ssize_t ret = sys_recvfrom(socket, buffer, length, flags, address, address_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_recv(int socket, void *buffer, size_t length, int flags);

ssize_t recv(int socket, void *buffer, size_t length, int flags) {
    ssize_t ret = sys_recv(socket, buffer, length, flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_send(int socket, const void *buffer, size_t length, int flags);

ssize_t send(int socket, const void *buffer, size_t length, int flags) {
    ssize_t ret = sys_send(socket, buffer, length, flags);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len);

ssize_t sendto(int socket, const void *message, size_t length, int flags, const struct sockaddr *dest_addr, socklen_t dest_len) {
    ssize_t ret = sys_sendto(socket, message, length, flags, dest_addr, dest_len);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/stat.h

int sys_fchmod(int fildes, mode_t mode);

int fchmod(int fildes, mode_t mode) {
    int ret = sys_fchmod(fildes, mode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_fstat(int fildes, struct stat *buf);

int fstat(int fildes, struct stat *buf) {
    int ret = sys_fstat(fildes, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_lstat(const char *restrict path, struct stat *restrict buf);

int lstat(const char *restrict path, struct stat *restrict buf) {
    int ret = sys_lstat(path, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_mkdir(const char *path, mode_t mode);

int mkdir(const char *path, mode_t mode) {
    int ret = sys_mkdir(path, mode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_stat(const char *restrict path, struct stat *restrict buf);

int stat(const char *restrict path, struct stat *restrict buf) {
    int ret = sys_stat(path, buf);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

mode_t sys_umask(mode_t __mask);

mode_t umask(mode_t __mask) {
    mode_t ret = sys_umask(__mask);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/time.h

int sys_gettimeofday(struct timeval *restrict tp, void *restrict tzp);

int gettimeofday(struct timeval *restrict tp, void *restrict tzp) {
    int ret = sys_gettimeofday(tp, tzp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// sys/uio.h

ssize_t sys_readv(int fildes, const struct iovec *iov, int iovcnt);

ssize_t readv(int fildes, const struct iovec *iov, int iovcnt) {
    ssize_t ret = sys_readv(fildes, iov, iovcnt);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_writev(int fildes, const struct iovec *iov, int iovcnt);

ssize_t writev(int fildes, const struct iovec *iov, int iovcnt) {
    ssize_t ret = sys_writev(fildes, iov, iovcnt);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// time.h

int sys_clock_getres(clockid_t clock_id, struct timespec *res);

int clock_getres(clockid_t clock_id, struct timespec *res) {
    int ret = sys_clock_getres(clock_id, res);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_clock_gettime(clockid_t clock_id, struct timespec *tp);

int clock_gettime(clockid_t clock_id, struct timespec *tp) {
    int ret = sys_clock_gettime(clock_id, tp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_clock_settime(clockid_t clock_id, const struct timespec *tp);

int clock_settime(clockid_t clock_id, const struct timespec *tp) {
    int ret = sys_clock_settime(clock_id, tp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_nanosleep(const struct timespec *rqtp, struct timespec *rmtp);

int nanosleep(const struct timespec *rqtp, struct timespec *rmtp) {
    int ret = sys_nanosleep(rqtp, rmtp);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

// unistd.h

int sys_access(const char *path, int mode);

int access(const char *path, int mode) {
    int ret = sys_access(path, mode);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_close(int fildes);

int close(int fildes) {
    int ret = sys_close(fildes);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_dup(int fildes);

int dup(int fildes) {
    int ret = sys_dup(fildes);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_dup2(int fildes, int fildes2);

int dup2(int fildes, int fildes2) {
    int ret = sys_dup2(fildes, fildes2);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

off_t sys_lseek(int fildes, off_t offset, int whence);

off_t lseek(int fildes, off_t offset, int whence) {
    off_t ret = sys_lseek(fildes, offset, whence);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_read(int fildes, void *buf, size_t nbyte);

ssize_t read(int fildes, void *buf, size_t nbyte) {
    ssize_t ret = sys_read(fildes, buf, nbyte);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_rmdir(const char *path);

int rmdir(const char *path) {
    int ret = sys_rmdir(path);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_truncate(const char *path, off_t length);

int truncate(const char *path, off_t length) {
    int ret = sys_truncate(path, length);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_ftruncate(int fd, off_t length);

int ftruncate(int fd, off_t length) {
    int ret = sys_ftruncate(fd, length);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

int sys_unlink(const char *path);

int unlink(const char *path) {
    int ret = sys_unlink(path);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}

ssize_t sys_write(int fildes, const void *buf, size_t nbyte);

ssize_t write(int fildes, const void *buf, size_t nbyte) {
    ssize_t ret = sys_write(fildes, buf, nbyte);

    if (ret < 0) {
        ret = -1;
    }

    return ret;
}
